### ISSUE TITLE
Since version 4.2.0 observe non confirmable not working properly

### ISSUE THREAD

**Issue by vincent-iQontrol** [shamblett/coap#107] opened 2022-07-06 12:04 UTC
I use a non confirmable observer from the example. Version 4.0.0 and 4.1.0 is working correctly, all events are coming in. In 4.2.0 and above a lot of events are missing after ~ 13 events.

final reqObsNon = CoapRequest(CoapCode.get, confirmable: false)..addUriPath('Json');

**Comment by JosefWN** [comment] 2022-07-07 08:44
Confirmed using this snippet (works in 4.1.0 but not in 4.2.0):
```dart
import 'dart:async';
import 'package:coap/coap.dart';
import 'config/coap_config.dart';

FutureOr main() async {
  final conf = CoapConfig();
  final uri = Uri(
    scheme: 'coap',
    host: 'californium.eclipseprojects.io',
    port: conf.defaultPort,
  );
  final client = CoapClient(uri, conf);

  try {
    final reqObsNon = CoapRequest(CoapCode.get, confirmable: false);
    reqObsNon.addUriPath('obs-non');

    print('Observing /obs-non on ${uri.host}');
    final obsNon = await client.observe(reqObsNon);
    obsNon.stream.listen((CoapRespondEvent e) {
      print('/obs-non response: ${e.resp.payloadString}');
    });

    await Future.delayed(Duration(minutes: 15));
  } catch (e) {
    print('CoAP encountered an exception: $e');
  }

  client.close();
}
```

I will try to dig into it soon.

**Comment by vincent-iQontrol** [comment] 2022-07-07 08:46
Thanks for investigating. I will use an older version for the time being.

**Comment by JosefWN** [comment] 2022-07-07 15:49
Made a couple of more test, this bug seems to have been introduced with my stricter linting of the repo...

**Comment by shamblett** [comment] 2022-07-07 17:57
Yep ok Ill look at the PRs over the weekend ta.

**Comment by shamblett** [comment] 2022-07-16 10:53
With this and #112 now merged are we ready for another release? There's quite a bitt gone since 4.2.1

**Comment by JosefWN** [comment] 2022-07-16 11:24
We could merge PR #111 too perhaps? Then I can rebase my other PR on master to reduce its size.

**Comment by JKRhb** [comment] 2022-07-16 11:40
> With this and #112 now merged are we ready for another release? There's quite a bitt gone since 4.2.1

I also have one or two more upcoming PRs which I will open soon, then we could go for a new release :)

**Comment by shamblett** [comment] 2022-07-16 11:54
OK PR #111 merged, I'll hold off on the release.

**Comment by JKRhb** [comment] 2022-07-17 17:39
> 
> I also have one or two more upcoming PRs which I will open soon, then we could go for a new release :)

Okay, I think I've now opened all PRs I had in flight :) Due to the fact that some of our PRs contain breaking changes, should we go for a 5.0.0 release?

**Comment by shamblett** [comment] 2022-08-12 12:24
Believe this has been addressed. Package re released at version 5.0.0.

**Comment by shamblett** [comment] 2022-10-29 07:47
Package now re published at version 6.0.0, closing this issue.

**Closed by shamblett** 2022-10-29 07:47 UTC
